### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by RaymondSWE** [RaymondSWE/ClassQueue#40]
# Step 2: Student Client
- [x] #127
- [x] #44
- [x]  Display the names of all students in the queue in the GUI.
- [x]  Update the list as new messages are received from the server.
- [x]  Display available supervisors in the GUI with status information.
- [x]  Show which student the supervisor is currently helping.
- [x]  Clearly display the user's place in the queue.
- [x]  Notify the user when it's their turn and display any message from the supervisor.
- [x]  Allow specifying the server and port for connection using a startup argument.
- [x]  Ensure compatibility with the Tinyqueue API.
- [x]  Connect to the server using ZMQ subscribe and request sockets.
- [x]  Send regular heartbeats to maintain position in the queue.
# Step 3: Server
- [x]  Implement the server application in a different programming language from the student client.
- [x]  Handle the queue state following a FIFO pattern.
- [x]  Accept new students entering the queue.
- [x]  Remove inactive users.
- [x]  Publish changes to all connected clients.
- [x]  Display events (connecting clients or queue changes) on standard out or server's GUI.
- [x]  Ensure student names are unique.
- [x]  Comply with the Tinyqueue API.
- [x] #45
- [x]  Allow multiple ZMQ clients for the same student.
# Step 4: Supervisor Client
- [x]  Implement a client for the supervisor.
- [x] #46
- [x]  Allow the supervisor to attend the student first in the queue.
- [x]  Allow the supervisor to specify a message for the student.
- [x]  Allow the supervisor to connect using a supervisor name.
- [x]  List all students in the queue.
- [x]  Display info about all connected supervisors.
- [x]  Document API extensions.
# Step 5: Reliability
- [x] #68
- [x] #138
- [x]  Remove clients that are inactive for more than T seconds.
- [x]  Handle short breaks in connection transparently.
- [x]  Reconnect clients transparently if the server crashes and restarts.
- [x]  Listen to ZMQ disconnects and re-connects events.
